mahseema/awesome-ai-tools

- README.md
Added [Keploy](https://www.keploy.io) to the list. It's an Open-source Tool for converting user traffic to Test Cases and Data Stubs. Hope that I've added it to the correct part of the readme!!
> Added Keploy

- README.md
Phind is an intelligent search engine and assistant for programmers. With Phind, you'll get the answer you're looking for in seconds instead of hours. It will guide you step-by-step from that idea in your head to a working app. Phind is smart enough to proactively ask you questions to clarify its assumptions and to browse the web (or your codebase) when it needs additional context.
With our new VS Code extension, you can now get Phind's help right in your editor.
> Add phind.com to "Chatbots". 

- README.md
Added:
- Stable Beluga model
- Petals platform
- Robert Miles AI safety youtube channel
> Several additions

- README.md
> Another AI image generator

- README.md
> Update README.md - Add VectortArt.ai

- README.md
add AI Character for GPT chrome extension to the directory for completeness
> add AI Character for GPT chrome extension to the directory

- README.md
> An AI based Search Engine

- README.md
For your consideration - a PR to add [Shotstack Workflows](https://shotstack.io/product/workflows/) to the list of tools.
> Add Shotstack Workflows

- README.md
> Add Listomatic.app

- README.md
Remove the space between [] and () to correct the link syntax
Resolve: #37
> Docs: Fix the bare url #37

- README.md
- [Kazimir.ai](https://kazimir.ai/) - A search engine designed to search AI-generated images.
> Added kazimir.ai

- README.md
Hi, 
please consider adding gensbot to your list,
Thanks and best,
Aurash
> add gensbot

- README.md
Adding Mutahunter to Code List
> Adding Mutahunter to Code List

- README.md
Add SVGStud.io
SVGStud.io is an AI-based tool for searching and generating Scalable Vector Graphics (SVGs) files.
> Add SVGStud.io

- README.md
I added new tool under the productivity category called Talently AI
> Added New Tool 

- README.md
Adding Adon smart recruiter to the list [Adon AI](https://adon-web.awakast.com/en/recruiter/)
> Add Adon AI

- README.md
added [Taranify Ai](https://www.taranify.com) to the awesome-ai-tools list.
Taranify uses a unique AI approach to find you [Spotify playlists](https://www.taranify.com/what-to-listen-spotify), [Netflix shows](https://www.taranify.com/what-to-watch-netflix), [Books](https://www.taranify.com/what-book-to-read) & [Foods](https://www.taranify.com/what-to-eat) you'd enjoy when you don't exactly know what you want. 
Its mantra is "Let's make boredom enjoyable" 
Thanks @mahseema for the awesome list.
> added www.taranify.com to the list

- README.md
added https://copilot.us/apps/chat-with-pdf
> added chat-with-pdf by copilot

- README.md
a vast collection of free AI-generated plant images, available for both personal and commercial use
thanks ;)
> add PlantPhotoAI.com

- README.md
https://github.com/mathiscode/ai-kernel-explorer
> Add AI Kernel Explorer to Code section

- README.md
(Not a maintainer, taken from their current description)
WhoDB is a lightweight (~20MB), powerful, and user-friendly database management tool designed to streamline your database administration tasks. Combining the simplicity of Adminer with enhanced UX and performance, WhoDB is built with GoLang to deliver optimal speed and efficiency. With features like interactive schema visualization and inline editing, WhoDB caters to both small projects and complex enterprise systems.
WhoDB offers you the opportunity to talk to your data using natural language thanks to our integration with Ollama, ChatGPT, and Anthropic. This feature allows you to perform queries and manage your data through conversation instead of complex SQL.
> Add new Code tool - WhoDB

- README.md
> Add Nexus AI to README.md

- README.md
> Added zenmic.com

- README.md
add Napkin to the other section
> add Napkin to the other section

- README.md
Wasn't sure if this should go here or under "other", but since there was another podcast related link in there it seemed right.
May want to make a separate section at some point for podcast :)
> Adds custompod.io to speech list

- README.md
Add RepublicLabs.ai as an image generation service
> Add RepublicLabs.ai as an image generation service

- README.md
Not my own, but still good AI tools and a list of AI tools for developers. Perhaps you would like to add them to your list.
Thank you for doing this.
> Add DeepL Write, SciSpace, Awesome AI-Powered Developer Tools

- README.md
Hi @mahseema, I added BrainSoup. Thanks for creating this awesome list!
> Add BrainSoup to Text / Productivity

- README.md
Add Suit me Up and AI Photo Forge to the directory.
> Add 2 links to directory

- README.md
Adding [Ollama ](https://ollama.com/) to developer tools. Ollma allows you to run LLMs locally within seconds.
> Adding Ollama

- README.md
I just added MindPal to the productivity category. MindPal is the platform to build AI agents and multi-agent workflow. By leveraging these agents, users can build their second brain.
You can check out the product here: https://mindpal.space/
> Add MindPal 

- README.md
> Added Trolly.ai

- README.md
Text2Infographic is an AI tool to generate infographics from simple text descriptions or a url (like a blog post for example)
> Add Text2Infographic to Graphic Design

- README.md
https://riffo.ai/
Riffo is a macOS application designed to simplify file management tasks by using GPT-4o to perform batch renaming, organize folders, and automatically group files into categories.
> Add New Productivity Tool - Riffo

- README.md
Added Publish7 AI agentic platform.
> Added publish7

- README.md
MindStudio lets you rapidly build, deploy, and operate AI Workers — automations, applications, agents. Anyone can build AI Workers rapidly (typically in under 30 minutes). Over 150k AI Workers are deployed across all types of use cases and organizations.
> Add MindStudio

- README.md
Learn more:
https://www.technologyreview.com/2024/04/25/1091835/chatbot-hallucination-new-tool-trustworthy-language-model/
https://analyticsindiamag.com/topics/top-ai-hallucination-detection-tools/
https://cleanlab.ai/blog/rag-tlm-hallucination-benchmarking/
https://labelstud.io/blog/llm-evaluation-comparing-four-methods-to-automatically-detect-errors/
https://github.com/cleanlab/cleanlab
> add cleanlab

- README.md
Thank you for the opportunity 🙏🏼
> Add Portia AI

- README.md
🧙‍♂️ **Terminal wizardry meets AI power\!**
Added poorcoder - the missing link between your terminal and AI assistants.
⭐ **Why poorcoder is awesome:**
- 🌱 Lightweight Bash scripts (Unix philosophy FTW\!)
- 🔄 Extract code context → Send to AI → Apply changes, all in your terminal
- 💸 Use your existing Claude/Grok subscriptions instead of expensive API calls
- 🛠️ Perfect for devs who love both their terminal AND AI assistance
Perfect for the terminal dwellers who want AI superpowers without switching contexts or breaking their workflow zen\!
> Add poorcoder to Code tools section

- marketing.md
Added AI Story Book :) An open source ai tool.
> added AI Story Book

- README.md
add [Audify AI](https://audify-ai.ahmedtokyo.com)
> ✨ add audify-ai

- README.md
This PR adds VoltAgent, an open-source TypeScript framework for building, orchestrating, and observing AI agents.
Repo: https://github.com/voltagent/voltagent
Docs: https://voltagent.dev
Thank you!
> feat: add VoltAgent

- README.md
Add [Notte](https://github.com/nottelabs/notte) - to the dev tool list
> Add notte to README.md

- README.md
Add https://www.magicpatterns.com/
Found from here:
[Launch HN: Magic Patterns (YC W23) – AI Design and Prototyping for Product Teams](https://news.ycombinator.com/item?id=43752176)
> Add https://www.magicpatterns.com/

- marketing.md
Added StoryShort.ai in Social Media Tool.
> Added StoryShort.ai in Social Media Tool

- README.md
Added [Melies](https://melies.co) for AI Filmmaking
> Add Melies AI

- README.md
I added MinusX to the productivity category. A lot of people struggle to get the data they need to do their job. MinusX is an open source chrome extension that reads your existing business context in Metabase so that it can reliably answer your data questions.
Website: https://minusx.ai/
Github: https://github.com/minusxai/minusx
> Add MinusX

- README.md
Added PhotoGuruAi.com for AI Headshot generator
> Add PhotoGuruAI

- README.md
Adding DataPup, a Database client powered by langchain to generate context aware SQL queries. 
Repo: https://github.com/DataPupOrg/DataPup
> Add DataPup to Code with AI

- README.md
- **Tool Name:**  AI Music Generator
- **Description:** (max 1 sentence)  AI Music Generator is an AI-powered platform that turns text and lyrics into custom songs. Create, remix, and produce royalty-free music effortlessly in various styles.
- **Tool URL:**  https://www.aisongmaker.io/
- **Altern.ai page link:** (if available)  
---
---
---
---
> Add aisongmaker.io

- README.md
Follow-up to: https://github.com/mahseema/awesome-ai-tools/pull/289
- **Tool Name:**  
- **Description:** (max 1 sentence)  
- **Tool URL:**  
- **Altern.ai page link:** (if available)  
---
---
---
---
> Add Agentset.ai 

- README.md
- **Tool Name:**  Rysa AI
- **Description:** AI GTM Automation Agent
- **Tool URL:** https://www.rysa.ai/  
- **Altern.ai page link:** (if available)  
Added a new AI tool to the "Developer Tools" section.
---
---
---
---
> Add Rysa AI
